server:
  port: 8080

spring:
  datasource:
    name:
      url: jdbc:mysql://127.0.0.1:3306/db_shopping?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml